# Generated by Django 3.1.3 on 2022-08-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_choicethree_choicetwo_questionthree_questiontwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicethree',
            name='question',
            field=models.ForeignKey(default='question', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.questionthree'),
        ),
        migrations.AlterField(
            model_name='choicetwo',
            name='question',
            field=models.ForeignKey(default='question', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.questiontwo'),
        ),
    ]
